path: "/home/wpotosna/m3_quarterly.csv"
name: "m3_quarterly"
horizon: 8
context_len: 16
val_size: 8
test_size: 15
weight: 1.0
hist_exog_cols: []
futr_exog_cols: []
stat_exog_cols: []
multivariate: False
