path: "/home/wpotosna/m4_monthly.csv"
name: "m4_monthly"
horizon: 18
context_len: 36
val_size: 18
test_size: 35
weight: 1.0
hist_exog_cols: []
futr_exog_cols: []
stat_exog_cols: []
multivariate: False
