path: "/home/wpotosna/simglucose_test_df2.csv"
name: "simglucose2"
horizon: 6
val_size: 200
test_size: 200
weight: 1.0
hist_exog_cols: [] #[CHO, insulin]
futr_exog_cols: []
stat_exog_cols: []
multivariate: False
