# General
model_type: cnn
tokenizer: none
input_layer: none
encoder: cnn
decoder: none
output_layer: linear_proj

# cnn encoder
context_len: 100
hidden_size: 256
dilations: [1, 2, 4, 8, 16] 
in_channels: 1  # CI: always 1 (series fed in one at a time)
kernel_size: 3      
patch_len: 1           
stride: 1 

# Regularization
dropout: 0.1
head_dropout: 0.0

# Normalization
revin: True
revin_affine: False
revin_subtract_last: False

# Other
activation: 'gelu'