# General
model_type: rnn
encoder: lstm
decoder: none
output_layer: linear_proj

# lstm encoder
d_model: 256
hidden_size: 256
n_layers: 4
dropout: 0.1
head_dropout: 0.0
revin: True
revin_affine: False
revin_subtract_last: False
activation: 'gelu'
