# General
model_type: rnn
tokenizer: none
input_layer: linear_proj
encoder: lstm
decoder: none
output_layer: linear_proj

# lstm encoder
hidden_size: 256
n_layers: 4
patch_len: 1           
stride: 1 

# Regularization
dropout: 0.1
head_dropout: 0.0

# Normalization
revin: True
revin_affine: False
revin_subtract_last: False
