# General
model_type: rnn
encoder: rnn 
decoder: none
output_layer: linear_proj

# rnn encoder
context_len: -1 #512
hidden_size: 256
n_layers: 4
patch_len: 1           
stride: 1 

# Regularization
dropout: 0.1
head_dropout: 0.0

# Normalization
revin: True
revin_affine: False
revin_subtract_last: False
