horizon_override: null
train:
  - ${load:configs/dataset/sources/simglucose.yaml}

validation:
  - ${load:configs/dataset/sources/simglucose.yaml}

test:
  - ${load:configs/dataset/sources/simglucose.yaml}