horizon_override: 6
n_channels: 30
train:
  - ${load:configs/dataset/sources/simglucose.yaml}

validation:
  - ${load:configs/dataset/sources/simglucose.yaml}

test:
  - ${load:configs/dataset/sources/simglucose.yaml}