# -----------------------------------------------------------
# ---------------------- Train datasets ---------------------
# -----------------------------------------------------------
train:
  - path: "../datasets/simglucose_90_days.csv"
    name: "simglucose"
    horizon: 6
    val_size: 2592 # 9 days (10% of data)
    test_size: 2592 # 9 days (10% of data)
    weight: 1
    hist_exog_cols: [CHO, insulin]
    #futr_exog_cols: []
    #stat_exog_cols: [region_id, store_type] # TODO @wpotosna
    per_series_split: False # Whether to split train/val/test based on timestpe (False) or unique per series (True)

# -----------------------------------------------------------
# ------------------- Validation datasets -------------------
# -----------------------------------------------------------
validation:
  - path: "../datasets/simglucose_90_days.csv"
    name: "simglucose"
    horizon: 6
    val_size: 2592 # 9 days (10% of data)
    test_size: 2592 # 9 days (10% of data)
    weight: 1
    hist_exog_cols: [CHO, insulin]
    #futr_exog_cols: []
    #stat_exog_cols: [region_id, store_type] # TODO @wpotosna
    per_series_split: False # Whether to split train/val/test based on timestpe (False) or unique per series (True)

# -----------------------------------------------------------
# ---------------------- Test datasets ----------------------
# -----------------------------------------------------------
test:
  - path: "../datasets/simglucose_90_days.csv"
    name: "simglucose"
    horizon: 6
    val_size: 2592 # 9 days (10% of data)
    test_size: 2592 # 9 days (10% of data)
    weight: 1
    hist_exog_cols: [CHO, insulin]
    #futr_exog_cols: []
    #stat_exog_cols: [region_id, store_type] # TODO @wpotosna
    per_series_split: False # Whether to split train/val/test based on timestpe (False) or unique per series (True)